In [28]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error,mean_squared_error
from sklearn.preprocessing import StandardScaler,OrdinalEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline 
from sklearn.impute import SimpleImputer
from sklearn.linear_model import Ridge,Lasso

In [29]:
df=pd.read_csv("StudentPerformanceFactors.csv")

In [30]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='str')

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   str
 11  Teacher_Quality             6529 non-null   str
 12  School_Type                 6607 non-null   str
 13  Peer_Influence              6607 non-null   str
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   str
 16  Parental_Education_Level    6517 non-null   str
 17  Distance_from_Home          6540 non-null   str
 18  Gender                      6607 non-null   str
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), str(13)
memory usage: 1.0 MB

In [32]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [33]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [34]:
df.tail()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [35]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [36]:
X=df.drop("Exam_Score",axis=1)
y=df["Exam_Score"]

In [37]:
ordinal_cols = [
    "Parental_Involvement",
    "Access_to_Resources",
    "Motivation_Level",
    "Family_Income",
    "Teacher_Quality",
    "Parental_Education_Level",
    "Distance_from_Home"
]

In [38]:
nominal_cols = [
    "Extracurricular_Activities",
    "Internet_Access",
    "School_Type",
    "Learning_Disabilities",
    "Gender",
    "Peer_Influence"
]

In [39]:
numeric_cols = [
    "Hours_Studied",
    "Attendance",
    "Sleep_Hours",
    "Previous_Scores",
    "Tutoring_Sessions",
    "Physical_Activity"
]

In [40]:
for col in df.select_dtypes(include='str').columns:
    print(col)
    print(df[col].unique())
    print()

Parental_Involvement
<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

Access_to_Resources
<StringArray>
['High', 'Medium', 'Low']
Length: 3, dtype: str

Extracurricular_Activities
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Motivation_Level
<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

Internet_Access
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

Family_Income
<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

Teacher_Quality
<StringArray>
['Medium', 'High', 'Low', nan]
Length: 4, dtype: str

School_Type
<StringArray>
['Public', 'Private']
Length: 2, dtype: str

Peer_Influence
<StringArray>
['Positive', 'Negative', 'Neutral']
Length: 3, dtype: str

Learning_Disabilities
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Parental_Education_Level
<StringArray>
['High School', 'College', 'Postgraduate', nan]
Length: 4, dtype: str

Distance_from_Home
<StringArray>
['Near', 'Moderate', 'Far', nan]
Length: 4, dtype: str

Gender
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [41]:
ordinal_pipeline=Pipeline([("imputer",SimpleImputer(strategy="constant",fill_value="Unknown")),
                           ("encoder",OrdinalEncoder(
                               categories=[
                                   ["Low","Medium","High"],
                                   ["Low","Medium","High"],
                                   ["Low","Medium","High"],
                                   ["Low","Medium","High"],
                                   ["Unknown","Low","Medium","High"],
                                   ["Unknown","High School","College","Postgraduate"],
                                   ["Unknown","Near","Moderate","Far"]
                               ]
                           )
                           )
                          ])

In [42]:
nominal_pipeline=Pipeline([
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("onehot",OneHotEncoder(handle_unknown="ignore"))
])

In [43]:
numeric_pipeline=Pipeline([
    ("imputer",SimpleImputer(strategy="median")),
    ("scaler",StandardScaler())
])

In [44]:
preprocessor=ColumnTransformer([
    ("num",numeric_pipeline,numeric_cols),
    ("ord",ordinal_pipeline,ordinal_cols),
    ("nom",nominal_pipeline,nominal_cols)
])

In [45]:
svr_pipeline=Pipeline([
    ("preprocessor",preprocessor),
    ("model",SVR(kernel='rbf',C=1.0,gamma='scale',epsilon=0.1)),
])

In [46]:
lr_pipeline=Pipeline([
    ("preprocessor",preprocessor),
    ("model",LinearRegression()),
])

In [47]:
rf_pipeline=Pipeline([
    ("preprocessor",preprocessor),
    ("model",RandomForestRegressor(n_estimators=300,max_depth=None,random_state=42,n_jobs=1)),
])

In [48]:
dt_pipeline=Pipeline([
    ("preprocessor",preprocessor),
    ("model",DecisionTreeRegressor(max_depth=5, min_samples_split=10,random_state=42)),
])

In [49]:
ridge_pipeline=Pipeline([
    ("preprocessor",preprocessor),
    ("model",Ridge(alpha=0.01)),
])

In [50]:
lasso_pipeline=Pipeline([
    ("preprocessor",preprocessor),
    ("model",Lasso(alpha=0.01)),
])

In [51]:
models={
    "Linear Regression": lr_pipeline,
    "SVR": svr_pipeline,
    "Random Forest": rf_pipeline,
    "Decision Tree": dt_pipeline,
    "Ridge Regression":ridge_pipeline,
    "Lasso Regression":lasso_pipeline
}

In [52]:
import numpy as np

In [53]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [54]:
results=[]
for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    r2=r2_score(y_test,y_pred)
    mae=mean_absolute_error(y_test,y_pred)
    rmse=np.sqrt(mean_squared_error(y_test,y_pred))
    results.append([name,r2,mae,rmse])

In [55]:
results_df = pd.DataFrame(
    results,
    columns=["Model", "R2", "MAE", "RMSE"]
)

print(results_df.sort_values(by="R2", ascending=False))

               Model        R2       MAE      RMSE
5   Lasso Regression  0.768491  0.472928  1.808977
4   Ridge Regression  0.768071  0.470430  1.810616
0  Linear Regression  0.768071  0.470430  1.810616
1                SVR  0.763432  0.496077  1.828637
2      Random Forest  0.676046  1.063399  2.139886
3      Decision Tree  0.544375  1.591736  2.537772

In [60]:
lasso_model=models["Lasso Regression"]
feature_names=lasso_model.named_steps["preprocessor"].get_feature_names_out()
coefficients=lasso_model.named_steps["model"].coef_

In [61]:
feature_names

array(['num__Hours_Studied', 'num__Attendance', 'num__Sleep_Hours',
       'num__Previous_Scores', 'num__Tutoring_Sessions',
       'num__Physical_Activity', 'ord__Parental_Involvement',
       'ord__Access_to_Resources', 'ord__Motivation_Level',
       'ord__Family_Income', 'ord__Teacher_Quality',
       'ord__Parental_Education_Level', 'ord__Distance_from_Home',
       'nom__Extracurricular_Activities_No',
       'nom__Extracurricular_Activities_Yes', 'nom__Internet_Access_No',
       'nom__Internet_Access_Yes', 'nom__School_Type_Private',
       'nom__School_Type_Public', 'nom__Learning_Disabilities_No',
       'nom__Learning_Disabilities_Yes', 'nom__Gender_Female',
       'nom__Gender_Male', 'nom__Peer_Influence_Negative',
       'nom__Peer_Influence_Neutral', 'nom__Peer_Influence_Positive'],
      dtype=object)

In [62]:
coef_df = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coefficients
})

coef_df["Abs_Coefficient"] = abs(coef_df["Coefficient"])

coef_df = coef_df.sort_values(
    by="Abs_Coefficient",
    ascending=False
)

print(coef_df)

                                Feature   Coefficient  Abs_Coefficient
1                       num__Attendance  2.282220e+00     2.282220e+00
0                    num__Hours_Studied  1.745086e+00     1.745086e+00
7              ord__Access_to_Resources  1.029752e+00     1.029752e+00
6             ord__Parental_Involvement  9.842190e-01     9.842190e-01
15              nom__Internet_Access_No -8.121001e-01     8.121001e-01
19        nom__Learning_Disabilities_No  7.534285e-01     7.534285e-01
3                  num__Previous_Scores  6.974971e-01     6.974971e-01
4                num__Tutoring_Sessions  6.160118e-01     6.160118e-01
13   nom__Extracurricular_Activities_No -5.373879e-01     5.373879e-01
23         nom__Peer_Influence_Negative -5.222990e-01     5.222990e-01
9                    ord__Family_Income  5.220647e-01     5.220647e-01
8                 ord__Motivation_Level  4.956217e-01     4.956217e-01
25         nom__Peer_Influence_Positive  4.620175e-01     4.620175e-01
11        ord__Parental_Education_Level  4.475010e-01     4.475010e-01
10                 ord__Teacher_Quality  4.426864e-01     4.426864e-01
12              ord__Distance_from_Home -4.113920e-01     4.113920e-01
5                num__Physical_Activity  1.843525e-01     1.843525e-01
2                      num__Sleep_Hours -1.067570e-02     1.067570e-02
20       nom__Learning_Disabilities_Yes -3.984646e-15     3.984646e-15
14  nom__Extracurricular_Activities_Yes  4.084261e-16     4.084261e-16
17             nom__School_Type_Private -0.000000e+00     0.000000e+00
16             nom__Internet_Access_Yes  0.000000e+00     0.000000e+00
21                   nom__Gender_Female  0.000000e+00     0.000000e+00
18              nom__School_Type_Public  0.000000e+00     0.000000e+00
22                     nom__Gender_Male -0.000000e+00     0.000000e+00
24          nom__Peer_Influence_Neutral -0.000000e+00     0.000000e+00

In [63]:
selected_features = [
    "Hours_Studied",
    "Attendance",
    "Parental_Involvement",
    "Access_to_Resources",
    "Previous_Scores",
    "Tutoring_Sessions",
    "Family_Income",
    "Motivation_Level",
    "Teacher_Quality",
    "Parental_Education_Level",
    "Distance_from_Home"
]